version: 1.0.{build}

branches:
  only:
    - master
    - 0.20.x

environment:
  matrix:
    - os: Visual Studio 2015
      GENERATOR_NAME: "Visual Studio 14 2015"
# TODO: Uncomment when AppVeyor will provide XP toolchain for VS2017
#    - os: Visual Studio 2017
#      GENERATOR_NAME: "Visual Studio 15 2017"

build:
  project: vk-cpp-bot.vcxproj
  verbosity: normal

configuration:
  - Release

before_build:
  - git submodule update --init vox thr py win32deps

after_build:
  - mkdir build
  - copy win32deps\libs\ build
  - copy vox build\
  - copy py build\
  - copy haarcascade_frontalface_default.xml build\
  - copy Release\vk-cpp-bot.exe build\
  # Create archive
  - 7z a -t7z vk-cpp-bot-win.7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on build
  - appveyor PushArtifact vk-cpp-bot-win.7z
  - curl --upload-file xash3d-win.7z https://transfer.sh/vk-cpp-bot-win.7z
